import React from 'react';
import { Download, FileCheck } from 'lucide-react';
import { Button } from '../ui/Button';
import { DiagnosisItem } from '../../types';
import { formatDate } from '../../lib/utils';

export interface PDFExporterProps {
  patientName: string;
  patientAge?: string;
  patientGender?: string;
  transcript: string;
  symptoms: string[];
  observations: string[];
  diagnoses: DiagnosisItem[];
}

export function PDFExporter({
  patientName,
  patientAge,
  patientGender,
  transcript,
  symptoms,
  observations,
  diagnoses
}: PDFExporterProps) {
  const handleExportPDF = () => {
    const printWindow = window.open('', '_blank');
    if (!printWindow) return;

    const htmlContent = `
      <!DOCTYPE html>
      <html>
        <head>
          <title>Clinical AI Consultation Report - ${patientName}</title>
          <style>
            body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; color: #1e293b; padding: 40px; line-height: 1.5; }
            .header { border-bottom: 2px solid #0d9488; padding-bottom: 15px; margin-bottom: 25px; display: flex; justify-content: space-between; align-items: center; }
            .title { font-size: 24px; font-weight: bold; color: #0f766e; }
            .subtitle { font-size: 12px; color: #64748b; }
            .section { margin-bottom: 25px; }
            .section-title { font-size: 14px; font-weight: bold; color: #0d9488; text-transform: uppercase; border-bottom: 1px solid #e2e8f0; padding-bottom: 5px; margin-bottom: 10px; }
            .patient-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 15px; background: #f8fafc; padding: 15px; border-radius: 8px; font-size: 13px; margin-bottom: 20px; }
            .chip { display: inline-block; background: #ccfbf1; color: #0f766e; padding: 4px 10px; border-radius: 15px; font-size: 12px; font-weight: 600; margin-right: 5px; margin-bottom: 5px; }
            .diag-card { border: 1fr solid #cbd5e1; background: #ffffff; padding: 15px; border-radius: 8px; margin-bottom: 12px; border-left: 4px solid #0d9488; }
            .diag-name { font-size: 15px; font-weight: bold; color: #0f172a; }
            .diag-confidence { font-size: 13px; font-weight: bold; color: #0d9488; float: right; }
            .tests-list { margin-top: 8px; font-size: 12px; color: #334155; }
            .footer { border-top: 1px solid #e2e8f0; pt: 15px; font-size: 11px; color: #94a3b8; text-align: center; margin-top: 40px; }
          </style>
        </head>
        <body>
          <div class="header">
            <div>
              <div class="title">MedAI Clinical Assistant</div>
              <div class="subtitle">AI Symptom Extraction & Differential Diagnosis Report</div>
            </div>
            <div style="text-align: right; font-size: 12px; color: #64748b;">
              <div>Date: ${formatDate(new Date().toISOString())}</div>
              <div>Report ID: CLIN-${Math.floor(100000 + Math.random() * 900000)}</div>
            </div>
          </div>

          <div class="patient-grid">
            <div><strong>Patient Name:</strong> ${patientName || 'Anonymous Patient'}</div>
            <div><strong>Age / Gender:</strong> ${patientAge || 'N/A'} Yrs / ${patientGender || 'Unspecified'}</div>
            <div><strong>Attending Doctor:</strong> Dr. Sarah Jenkins, MD</div>
          </div>

          <div class="section">
            <div class="section-title">Extracted Symptoms</div>
            <div>
              ${symptoms.map((s) => `<span class="chip">✓ ${s}</span>`).join('')}
            </div>
          </div>

          <div class="section">
            <div class="section-title">Clinical Observations & History</div>
            <ul style="font-size: 13px; color: #334155; padding-left: 20px;">
              ${observations.map((o) => `<li>${o}</li>`).join('')}
            </ul>
          </div>

          <div class="section">
            <div class="section-title">Top 3 AI Differential Diagnoses</div>
            ${diagnoses
              .map(
                (d, i) => `
                <div class="diag-card">
                  <span class="diag-confidence">Confidence: ${d.confidence}</span>
                  <div class="diag-name">#${i + 1} ${d.name}</div>
                  <div class="tests-list">
                    <strong>Recommended Tests:</strong> ${d.recommendedTests.join(', ')}
                  </div>
                </div>
              `
              )
              .join('')}
          </div>

          <div class="section">
            <div class="section-title">Interaction Transcript</div>
            <pre style="white-space: pre-wrap; font-family: monospace; font-size: 11px; background: #f1f5f9; padding: 15px; border-radius: 6px;">${transcript}</pre>
          </div>

          <div class="footer">
            Generated by MedAI Clinical System (Advanced Audio Transcription & State-of-the-art Disease Prediction AI). Confirmed by attending physician.
          </div>
        </body>
      </html>
    `;

    printWindow.document.write(htmlContent);
    printWindow.document.close();
    printWindow.focus();
    setTimeout(() => {
      printWindow.print();
    }, 500);
  };

  return (
    <Button
      variant="outline"
      size="sm"
      onClick={handleExportPDF}
      leftIcon={<Download className="h-3.5 w-3.5 text-teal-400" />}
    >
      Export PDF
    </Button>
  );
}
