export const INCIDENT_PERMISSIONS = {
  CREATE: 'INCIDENT:INCIDENTS:CREATE',
  READ: 'INCIDENT:INCIDENTS:READ',
  UPDATE: 'INCIDENT:INCIDENTS:UPDATE',
  DELETE: 'INCIDENT:INCIDENTS:DELETE',
  ASSIGN: 'INCIDENT:INCIDENTS:ASSIGN',
  CLOSE: 'INCIDENT:INCIDENTS:CLOSE',
  INVESTIGATE: 'INCIDENT:INVESTIGATIONS:MANAGE',
  RCA_MANAGE: 'INCIDENT:RCA:MANAGE',
  CAPA_MANAGE: 'INCIDENT:CAPA:MANAGE',
  VERIFY: 'INCIDENT:CAPA:VERIFY',
  DASHBOARD: 'INCIDENT:DASHBOARD:READ',
  SETTINGS: 'INCIDENT:SETTINGS:MANAGE',
} as const;

export type IncidentPermission = typeof INCIDENT_PERMISSIONS[keyof typeof INCIDENT_PERMISSIONS];
