import { Inject, Injectable, Logger, Optional } from '@nestjs/common';
import { InjectQueue } from '@nestjs/bull';
import { Queue } from 'bull';
import { IOracleTransport } from '../../platform/infrastructure/oracle/oracle-transport.interface';
import { ORACLE_TRANSPORT } from '../../platform/infrastructure/tokens';
import { InjectRedis } from '../../../common/redis/redis.provider';
import type { Redis } from 'ioredis';

export interface PrintDataDetailPayload {
  tokenNumber: number;
  locationId: string;
  locationCode: string;
  locationName: string;
  printedAt: Date;
  departmentId?: number | string | null;
  departmentName?: string | null;
  serviceCenterId?: number | string | null;
  serviceCenterName?: string | null;
  intrabranchId?: number | string | null;
}

export interface HisDepartment {
  departmentId: number | string;
  departmentName: string;
  intrabranchId: number | string;
}

export interface HisServiceCenter {
  serviceCenterId: number | string;
  serviceCenterName: string;
  departmentId: number | string;
  intrabranchId: number | string;
}

/**
 * HisTokenBridgeService
 *
 * Inserts a row into PRINT_DATA_DETAIL in the HIS Main Oracle database
 * every time a token is issued at the kiosk.
 *
 * Create the target table in Oracle once using:
 *
 *   CREATE TABLE PRINT_DATA_DETAIL (
 *     ID             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 *     TOKEN_NUMBER   NUMBER(10)    NOT NULL,
 *     LOCATION_ID    VARCHAR2(100) NOT NULL,
 *     LOCATION_CODE  VARCHAR2(50)  NOT NULL,
 *     LOCATION_NAME  VARCHAR2(255) NOT NULL,
 *     PRINTED_AT     TIMESTAMP     NOT NULL,
 *     CREATED_AT     TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL
 *   );
 *
 *   CREATE INDEX IDX_PDD_LOCATION ON PRINT_DATA_DETAIL (LOCATION_ID);
 *   CREATE INDEX IDX_PDD_PRINTED  ON PRINT_DATA_DETAIL (PRINTED_AT);
 *
 * Query from HIS:
 *   SELECT * FROM PRINT_DATA_DETAIL
 *   WHERE LOCATION_ID = :locationId
 *   ORDER BY PRINTED_AT DESC;
 */
@Injectable()
export class HisTokenBridgeService {
  private readonly logger = new Logger(HisTokenBridgeService.name);

  constructor(
    @Inject(ORACLE_TRANSPORT) private readonly oracle: IOracleTransport,
    @InjectQueue('his-bridge') private readonly bridgeQueue: Queue,
    @Optional() @InjectRedis() private readonly redis?: Redis,
  ) { }

  // ── HIS lookup helpers ──────────────────────────────────────────────────────

  /**
   * Short TTL for department/service-center reference data. This data
   * changes rarely (new departments/service centers aren't added mid-shift),
   * but every dropdown open was previously hitting Oracle fresh -- with no
   * circuit breaker at the time, a flaky/slow Oracle meant every kiosk/
   * workstation config screen waited out a full connection timeout on every
   * single load. Caching for a minute means only the first load per branch
   * per minute pays that cost; everything else is instant.
   */
  private static readonly REFERENCE_CACHE_TTL_S = 60;

  private async getCached<T>(key: string): Promise<T | null> {
    if (!this.redis) return null;
    try {
      const raw = await this.redis.get(key);
      return raw ? (JSON.parse(raw) as T) : null;
    } catch {
      return null;
    }
  }

  private async setCached(key: string, value: unknown): Promise<void> {
    if (!this.redis) return;
    try {
      await this.redis.setex(key, HisTokenBridgeService.REFERENCE_CACHE_TTL_S, JSON.stringify(value));
    } catch {
      // Cache write failures should never break the actual lookup
    }
  }

  /**
   * Returns departments from Oracle filtered by intrabranchId (branch/site).
   */
  async getDepartments(intrabranchId: string | number): Promise<HisDepartment[]> {
    const cacheKey = `his:departments:${intrabranchId}`;
    const cached = await this.getCached<HisDepartment[]>(cacheKey);
    if (cached) return cached;

    if (!this.oracle.isAvailable) {
      this.logger.warn('Oracle unavailable — cannot fetch departments');
      return [];
    }
    try {
      const rows = await this.oracle.query<{ DEPARTMENT_ID: unknown; DEPARTMENT_NAME: unknown; INTRABRANCHID: unknown }>(
        `SELECT department_id, department_name, intrabranchid
           FROM hisdepartment
          WHERE active = 1
            AND intrabranchid = :intrabranchId
          ORDER BY department_name`,
        { intrabranchId },
      );
      const departments = rows.map((r) => ({
        departmentId: r.DEPARTMENT_ID as number | string,
        departmentName: String(r.DEPARTMENT_NAME ?? ''),
        intrabranchId: r.INTRABRANCHID as number | string,
      }));
      await this.setCached(cacheKey, departments);
      return departments;
    } catch (err) {
      this.logger.error(`getDepartments failed: ${(err as Error).message}`);
      return [];
    }
  }

  /**
   * Returns service centers from Oracle, optionally filtered by department and branch.
   */
  async getServiceCenters(
    intrabranchId: string | number,
    departmentId?: string | number | null,
  ): Promise<HisServiceCenter[]> {
    const cacheKey = `his:service-centers:${intrabranchId}:${departmentId ?? 'all'}`;
    const cached = await this.getCached<HisServiceCenter[]>(cacheKey);
    if (cached) return cached;

    if (!this.oracle.isAvailable) {
      this.logger.warn('Oracle unavailable -- cannot fetch service centers');
      return [];
    }
    try {
      const binds: Record<string, unknown> = { intrabranchId };
      // The FK column in Oracle is named `department` (not `department_id`) --
      // aliased below so the row-mapping code can keep reading DEPARTMENT_ID.
      // Previously this query selected/filtered on the nonexistent
      // `department_id` column, which Oracle rejects with ORA-00904 on every
      // call; the try/catch below silently swallowed that and returned an
      // empty list every time, so the Service Center dropdown never populated
      // for ANY department -- not just this one.
      let sql = `SELECT service_center_id, service_center_name, department_id AS department_id, intrabranchid
                   FROM servicecenter
                  WHERE active = 1
                    AND intrabranchid = :intrabranchId`;
      if (departmentId != null) {
        sql += ` AND department_id = :departmentId`;
        binds['departmentId'] = departmentId;
      }
      sql += ` ORDER BY service_center_name`;

      const rows = await this.oracle.query<{
        SERVICE_CENTER_ID: unknown;
        SERVICE_CENTER_NAME: unknown;
        DEPARTMENT_ID: unknown;
        INTRABRANCHID: unknown;
      }>(sql, binds);

      const serviceCenters = rows.map((r) => ({
        serviceCenterId: r.SERVICE_CENTER_ID as number | string,
        serviceCenterName: String(r.SERVICE_CENTER_NAME ?? ''),
        departmentId: r.DEPARTMENT_ID as number | string,
        intrabranchId: r.INTRABRANCHID as number | string,
      }));
      await this.setCached(cacheKey, serviceCenters);
      return serviceCenters;
    } catch (err) {
      this.logger.error(`getServiceCenters failed: ${(err as Error).message}`);
      return [];
    }
  }

  /**
   * Resolves a single department by ID, direct from Oracle -- no `active`
   * filter, no intrabranchid filter. Used as a fallback when a HIS-selected
   * department ID (passed via SSO auto-login) isn't present in the filtered
   * getDepartments() list, so the UI can still show the real name instead of
   * a bare numeric ID, regardless of why the general list excluded it.
   */
  async getDepartmentById(departmentId: string | number): Promise<HisDepartment | null> {
    if (!this.oracle.isAvailable) return null;
    try {
      const rows = await this.oracle.query<{ DEPARTMENT_ID: unknown; DEPARTMENT_NAME: unknown; INTRABRANCHID: unknown }>(
        `SELECT department_id, department_name, intrabranchid
           FROM hisdepartment
          WHERE department_id = :departmentId`,
        { departmentId },
      );
      const row = rows[0];
      if (!row) return null;
      return {
        departmentId:   row.DEPARTMENT_ID as number | string,
        departmentName: String(row.DEPARTMENT_NAME ?? ''),
        intrabranchId:  row.INTRABRANCHID as number | string,
      };
    } catch (err) {
      this.logger.error(`getDepartmentById failed: ${(err as Error).message}`);
      return null;
    }
  }

  /**
   * Resolves a single service center by ID, direct from Oracle -- no `active`
   * filter. Same rationale as getDepartmentById(). Uses the same `department`
   * (not `department_id`) column fix as getServiceCenters().
   */
  async getServiceCenterById(serviceCenterId: string | number): Promise<HisServiceCenter | null> {
    if (!this.oracle.isAvailable) return null;
    try {
      const rows = await this.oracle.query<{
        SERVICE_CENTER_ID: unknown;
        SERVICE_CENTER_NAME: unknown;
        DEPARTMENT_ID: unknown;
        INTRABRANCHID: unknown;
      }>(
        `SELECT service_center_id, service_center_name, department AS department_id, intrabranchid
           FROM servicecenter
          WHERE service_center_id = :serviceCenterId`,
        { serviceCenterId },
      );
      const row = rows[0];
      if (!row) return null;
      return {
        serviceCenterId:   row.SERVICE_CENTER_ID as number | string,
        serviceCenterName: String(row.SERVICE_CENTER_NAME ?? ''),
        departmentId:      row.DEPARTMENT_ID as number | string,
        intrabranchId:     row.INTRABRANCHID as number | string,
      };
    } catch (err) {
      this.logger.error(`getServiceCenterById failed: ${(err as Error).message}`);
      return null;
    }
  }

  // -- Print record insert -----------------------------------------------------

  /**
   * Inserts one row into PRINT_DATA_DETAIL.
   * Fire-and-forget -- never throws, so the kiosk flow is never blocked by
   * an Oracle connectivity issue.
   */
  /**
   * Fire-and-forget entry point called from TokenService.
   * On Oracle unavailability or failure, enqueues for retry via Bull
   * instead of silently dropping the record (GAP-7).
   */
  async insertPrintRecord(payload: PrintDataDetailPayload): Promise<void> {
    this.logger.log(
      `[BRIDGE] insertPrintRecord called -- token=${payload.tokenNumber} ` +
      `location=${payload.locationCode} oracleAvailable=${this.oracle.isAvailable}`,
    );

    if (!this.oracle.isAvailable) {
      this.logger.warn(
        `HIS Oracle unavailable -- queuing PRINT_DATA_DETAIL insert for token ${payload.tokenNumber}`,
      );
      await this.enqueueRetry(payload);
      return;
    }

    try {
      const insertSql = `
        INSERT INTO PRINT_DATA_DETAIL (
          TOKEN_NUMBER,
          LOCATION_ID,
          LOCATION_CODE,
          LOCATION_NAME,
          PRINTED_AT,
          DEPARTMENT_ID,
          DEPARTMENT_NAME,
          SERVICE_CENTER_ID,
          SERVICE_CENTER_NAME,
          INTRABRANCHID,
          CREATED_AT
        ) VALUES (
          :tokenNumber,
          :locationId,
          :locationCode,
          :locationName,
          :printedAt,
          :departmentId,
          :departmentName,
          :serviceCenterId,
          :serviceCenterName,
          :intrabranchId,
          SYSTIMESTAMP
        )
      `;

      const binds = {
        tokenNumber: payload.tokenNumber,
        locationId: payload.locationId,
        locationCode: payload.locationCode,
        locationName: payload.locationName,
        printedAt: payload.printedAt,
        departmentId: payload.departmentId ?? null,
        departmentName: payload.departmentName ?? null,
        serviceCenterId: payload.serviceCenterId ?? null,
        serviceCenterName: payload.serviceCenterName ?? null,
        intrabranchId: payload.intrabranchId ?? null,
      };

      const rowsAffected = await this.oracle.execute(insertSql, binds);

      this.logger.log(
        `PRINT_DATA_DETAIL inserted -- token=${payload.tokenNumber} ` +
        `location=${payload.locationCode} rowsAffected=${rowsAffected}`,
      );
    } catch (err) {
      this.logger.error(
        `Failed to insert PRINT_DATA_DETAIL for token ${payload.tokenNumber} ` +
        `at location ${payload.locationCode}: ${(err as Error).message} -- queuing for retry`,
      );
      await this.enqueueRetry(payload);
    }
  }

  /**
   * Direct Oracle insert -- called by HisBridgeProcessor on retry.
   * Unlike insertPrintRecord, this method throws on failure so Bull can retry.
   */
  async insertPrintRecordDirect(payload: PrintDataDetailPayload): Promise<void> {
    const insertSql = `
      INSERT INTO PRINT_DATA_DETAIL (
        TOKEN_NUMBER, LOCATION_ID, LOCATION_CODE, LOCATION_NAME,
        PRINTED_AT, DEPARTMENT_ID, DEPARTMENT_NAME,
        SERVICE_CENTER_ID, SERVICE_CENTER_NAME, INTRABRANCHID, CREATED_AT
      ) VALUES (
        :tokenNumber, :locationId, :locationCode, :locationName,
        :printedAt, :departmentId, :departmentName,
        :serviceCenterId, :serviceCenterName, :intrabranchId, SYSTIMESTAMP
      )
    `;
    const binds = {
      tokenNumber: payload.tokenNumber,
      locationId: payload.locationId,
      locationCode: payload.locationCode,
      locationName: payload.locationName,
      printedAt: payload.printedAt,
      departmentId: payload.departmentId ?? null,
      departmentName: payload.departmentName ?? null,
      serviceCenterId: payload.serviceCenterId ?? null,
      serviceCenterName: payload.serviceCenterName ?? null,
      intrabranchId: payload.intrabranchId ?? null,
    };
    await this.oracle.execute(insertSql, binds);
  }

  private async enqueueRetry(payload: PrintDataDetailPayload): Promise<void> {
    try {
      await this.bridgeQueue.add('insert-print-record', payload, {
        attempts: 5,
        backoff: { type: 'exponential', delay: 30_000 }, // 30s, 60s, 120s, 240s, 480s
        removeOnComplete: 100,
        removeOnFail: false,
      });
    } catch (qErr) {
      // Queue push should never crash the kiosk flow
      this.logger.error(
        `Failed to enqueue his-bridge retry for token ${payload.tokenNumber}: ${(qErr as Error).message}`,
      );
    }
  }
}
