# Secrets Manager secret *shells* -- Terraform creates the secret objects
# with a placeholder JSON value; the real values are populated manually
# (AWS console/CLI) or by a CI/CD pipeline (Phase 12) AFTER apply, never
# committed as Terraform literals in this repo. `lifecycle.ignore_changes`
# on each secret_version prevents a future `terraform apply` from
# clobbering values populated out-of-band.

resource "aws_secretsmanager_secret" "rds_connection" {
  name = "hdsp/rds-connection"
}

resource "aws_secretsmanager_secret_version" "rds_connection" {
  secret_id = aws_secretsmanager_secret.rds_connection.id
  secret_string = jsonencode({
    host     = aws_db_instance.hdsp.address
    port     = aws_db_instance.hdsp.port
    dbname   = var.db_name
    username = var.db_master_username
    password = random_password.db_master.result
  })
  # password/host are populated for real by the resources above -- this
  # secret is the one exception where Terraform DOES manage the real
  # value, since it's generated by `random_password` rather than a
  # human-provisioned credential (SES/SNS keys, etc. below).
}

resource "aws_secretsmanager_secret" "elasticache_connection" {
  name = "hdsp/elasticache-connection"
}

resource "aws_secretsmanager_secret_version" "elasticache_connection" {
  secret_id = aws_secretsmanager_secret.elasticache_connection.id
  secret_string = jsonencode({
    host        = aws_elasticache_replication_group.hdsp.primary_endpoint_address
    port        = 6379
    authToken   = random_password.redis_auth.result
    # rediss:// (TLS) scheme + embedded auth token -- see
    # infrastructure/ecs/connector-task-definition.json's _redis_tls_note
    # and redis.config.ts's `tls` doc comment for why the backend needs a
    # separate REDIS_TLS=true flag instead of a URL scheme.
    connectorUrl = "rediss://:${random_password.redis_auth.result}@${aws_elasticache_replication_group.hdsp.primary_endpoint_address}:6379"
  })
}

resource "aws_secretsmanager_secret" "jwt" {
  name = "hdsp/jwt"
}

resource "aws_secretsmanager_secret_version" "jwt" {
  secret_id = aws_secretsmanager_secret.jwt.id
  # Placeholder only -- generate real values the same way DEPLOY.md's
  # self-hosted runbook does (`node -e "console.log(require('crypto').randomBytes(64).toString('hex'))"`)
  # and update this secret manually (or via CI/CD, Phase 12) before the
  # first real deploy. NEVER reuse a self-hosted install's JWT secret here.
  #
  # `vendorPortalApiKey` (Cloud Tenant Onboarding -- see
  # CLOUD_TENANT_ONBOARDING_DESIGN.md, VendorPortalApiKeyGuard) is
  # co-located here rather than in `hdsp/app-config`: it's the same
  # category of thing as `secret`/`refreshSecret` above -- a
  # manually-provisioned, security-sensitive credential that must never be
  # a Terraform literal -- unlike app_config's other fields, which are
  # real Terraform-derived values. Generate it the same way (a long random
  # string), matching Vendor Portal's own configuration for the same
  # value (see vendor-portal's deployment docs, once its consuming side
  # exists -- Cloud Tenant Onboarding Phase B).
  secret_string = jsonencode({
    secret             = "REPLACE_ME_BEFORE_FIRST_DEPLOY"
    refreshSecret      = "REPLACE_ME_BEFORE_FIRST_DEPLOY_DIFFERENT_VALUE"
    vendorPortalApiKey = "REPLACE_ME_BEFORE_FIRST_DEPLOY_DIFFERENT_VALUE"
  })

  lifecycle {
    ignore_changes = [secret_string]
  }
}

resource "aws_secretsmanager_secret" "aws_notifications" {
  name = "hdsp/aws-notifications"
}

resource "aws_secretsmanager_secret_version" "aws_notifications" {
  secret_id = aws_secretsmanager_secret.aws_notifications.id
  # Phase 5's CloudNotificationProvider (SES/SNS) credentials -- placeholder;
  # populate with a dedicated IAM user/role's keys scoped to
  # ses:SendEmail/sns:Publish only, matching ecs.tf's task-role policy.
  secret_string = jsonencode({
    accessKeyId     = "REPLACE_ME"
    secretAccessKey = "REPLACE_ME"
    sesFromEmail    = "REPLACE_ME_verified_ses_identity@example.com"
  })

  lifecycle {
    ignore_changes = [secret_string]
  }
}

resource "aws_secretsmanager_secret" "app_config" {
  name = "hdsp/app-config"
}

resource "aws_secretsmanager_secret_version" "app_config" {
  secret_id = aws_secretsmanager_secret.app_config.id
  secret_string = jsonencode({
    s3Bucket        = aws_s3_bucket.hdsp.bucket
    cloudBaseDomain = var.cloud_base_domain
  })
  # NOTE: unlike hdsp/jwt below, both fields here are real Terraform-derived
  # values (not manually-provisioned secrets), so this deliberately has NO
  # `lifecycle.ignore_changes` -- a future `terraform apply` correctly keeps
  # them in sync with the underlying bucket/variable. Do not add
  # manually-provisioned secrets (like vendorPortalApiKey below) into this
  # secret -- that would force adding `ignore_changes` here too, which
  # would then also freeze s3Bucket/cloudBaseDomain from ever being
  # updated by Terraform again. Manual credentials belong in `hdsp/jwt`
  # (already `ignore_changes`-protected) or a new dedicated secret.
}

# Per-hospital Oracle credentials for a Connector instance (see
# infrastructure/ecs/connector-task-definition.json) -- one secret per
# tenant, created out-of-band during Phase 10's (not this phase's) tenant
# onboarding flow. Not managed here; noted for completeness only.
