export enum LogoutReason {
  MANUAL = 'MANUAL',
  IDLE_TIMEOUT = 'IDLE_TIMEOUT',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  TOKEN_REVOKED = 'TOKEN_REVOKED',
  ACCOUNT_DISABLED = 'ACCOUNT_DISABLED',
  LICENSE_EXPIRED = 'LICENSE_EXPIRED',
  TENANT_SUSPENDED = 'TENANT_SUSPENDED',
  MAINTENANCE_MODE = 'MAINTENANCE_MODE',
  FORCE_LOGOUT = 'FORCE_LOGOUT',
  PASSWORD_CHANGED = 'PASSWORD_CHANGED',
  SYSTEM_SHUTDOWN = 'SYSTEM_SHUTDOWN'
}
